/* Edit for testing */
#include<graphics.h>
void main()
{
int x=320,y,r=2,gd=DETECT,gm;
initgraph(&gd,&gm,"");

while(!kbhit())
{
for(y=200;y>50;y-=5)
{
setcolor(LIGHTGRAY);
setbkcolor(BLACK);
setfillstyle(SOLID_FILL,LIGHTGRAY);
circle(x,y,r);
floodfill(x,y,LIGHTGRAY);
delay(40);
setfillstyle(SOLID_FILL,BLACK);
setcolor(BLACK);
circle(x,y,r);
floodfill(x,y,BLACK);
r++;
}
for(y=50;y<200;y+=5)
{
setcolor(LIGHTGRAY);
setbkcolor(BLACK);
setfillstyle(SOLID_FILL,LIGHTGRAY);
circle(x,y,r);
floodfill(x,y,LIGHTGRAY);
delay(40);
setcolor(BLACK);
setfillstyle(SOLID_FILL,BLACK);
circle(x,y,r);
floodfill(x,y,BLACK);
r++;
}
for(y=200;y<350;y+=5)
{
setcolor(LIGHTGRAY);
setbkcolor(BLACK);
setfillstyle(SOLID_FILL,LIGHTGRAY);
circle(x,y,r);
floodfill(x,y,LIGHTGRAY);
delay(40);
setcolor(BLACK);
setfillstyle(SOLID_FILL,BLACK);
circle(x,y,r);
floodfill(x,y,BLACK);
r--;
}
for(y=350;y>200;y-=5)
{
setcolor(LIGHTGRAY);
setbkcolor(BLACK);
setfillstyle(SOLID_FILL,LIGHTGRAY);
circle(x,y,r);
floodfill(x,y,LIGHTGRAY);
delay(40);
setcolor(BLACK);
setfillstyle(SOLID_FILL,BLACK);
circle(x,y,r);
floodfill(x,y,BLACK);
r--;
}
}
    closegraph();
    restorecrtmode();
}
